viv_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['viv_wheel_front_left_joint', 'viv_wheel_rear_left_joint']
  right_wheel: ['viv_wheel_front_right_joint', 'viv_wheel_rear_right_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.25

  # Base frame_id
  base_frame_id: viv_base

  enable_odom_tf: true

  estimate_velocity_from_position: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  publish_cmd : true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.65   # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.2   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 0.5   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.0   # rad/s^2
